To Do List features
guillainbisimwa/To-Do-List pull request #3
Opened 2021-02-25 17:07 UTC by Blaise-Shyaka

In this project, we have done the following:
- Created factory functions to handle the creation of project and task instances
- Created the user interface
- Generated DOM elements using JavaScript
- Added DOM event handlers

2021-02-25 21:33 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Blaise-Shyaka and @guillainbisimwa, great job on this project :muscle: The App looks great, the functionality works as expected, we can delete, add, edit a task, we can do the same to the project as well :smile: Awesome. The README file is very professional with a working live link :100: The PR has a meaningful title and a short description :fireworks: Commit messages are great and easy to understand :1st_place_medal: Great implementation of the single responsibility design pattern :slightly_smiling_face: 
However, we have a few comments we need to address before proceeding, kindly check the comments below:

- Kindly implement localStorage so the data remains in the browser even when we refresh the browser. Let us implement this :+1: 
- Kindly add webpack-dev-server to our package.json file
- Kindly use ES6 arrow function

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/headerComponent.js
> +export default function createHeader() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/modalComponent.js
> +export function addProjectModal() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/modalComponent.js
> +export function deleteProjectModal() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/projectComponent.js
> +function allProjectTasks(projectId, tasksList) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/projectComponent.js
> +export default function displayProject(projectId, project) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/taskComponent.js
> +export default function displayTask(
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/taskModalComponent.js
> +export function addTaskModal() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/taskModalComponent.js
> +  // });
Kindly remove commented code :smile:

2021-02-25 21:33 UTC, addod19 commented on src/scripts/components/taskModalComponent.js
> +export function deleteTaskModal() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addProject.js
> +function cleanForm(elts = []) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addProject.js
> +function handleGeneratingNewInstance() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addProject.js
> +function handleAddingProject() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addProject.js
> +function addProject() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addTask.js
> +function handleAddingTask(event) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/addTask.js
> +function handleAdd() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/deleteProject.js
> +function handleDeletingProject(event) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/deleteProject.js
> +export function handleDeleteProject() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/deleteTask.js
> +function handleDeletingTask(event) {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on src/scripts/dom-handlers/deleteTask.js
> +export default function deleteTask() {
Kindly use ES6 arrow function instead

2021-02-25 21:33 UTC, addod19 commented on package.json
> +    "webpack-cli": "^4.5.0"
Kindly add `webpack-dev-server` to our ppackage.json file :muscle:

2021-02-25 21:33 UTC, addod19 commented on package.json
> +  },
Let us replace our script from 
````
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "watch": "webpack --watch"
  }

 to 

"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

2021-03-01 00:48 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello team,
Great work on this project. The UI is 👌 and the app runs smoothly.
However small changes are required to make it even more outstanding.

[REQUIRED]: Kindly save data in the localStorage. This will prevent the loss of data after refreshing a page.

Make the requested changes and ask for another review👌👌👌
Happy coding 💻

2021-03-01 11:20 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-03-01 11:44 UTC, merged